"""empty message

Revision ID: 663294b52e05
Revises: 32ad433db468
Create Date: 2023-07-03 00:07:41.696705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663294b52e05'
down_revision = '32ad433db468'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auction', 'fee',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auction', 'fee',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
